#配置服务器信息
server:
  port: 8002
#数据库信息配置
spring:
  application:
    name: study-springcloud-dept  #微服务名称
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb02?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型

    #druid连接池配置
    initialSize: 5  #初始化连接数
    minIdle: 5      #数据库连接池最小连接维持数
    maxActive: 20   #数据库最大活动连接数
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters,去掉监控界面sql无法统计，‘wall’用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    userGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#Mybatis配置
mybatis:
  #type-aliases-package: com.blj.springcloud.entities        #所有Entities实体类别名所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml        #mapper映射文件

  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    cache-enabled: true #开启二级缓存
  type-aliases-package: com.blj.springcloud.entities        #所有Entities实体类别名所在包

#客户端注册进eureka服务列表
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka ,http://localhost:7004/eureka,http://localhost:7003/eureka

  instance:
    instance-id:  cloud-dept8002 #自定义服务名称信息
    prefer-ip-address: true   #访问路径可以显示ip地址
info:
  app.name: study-springcloud-dept
  company.name: www.blj.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}